### ISSUE TITLE
website design

### ISSUE THREAD

**Issue by ashadnasim52** [akiraux/website#3]
Want to work on this project website. Can I built this website in "Gatsby" or just "Reactjs". Or Nuxtjs is required.

Also, if you can add the design of the UI of the website then it would be easy for me to work.

Sorry, but this would be my first Open Source contribution

**Comment by albfan** [comment]
Follow https://github.com/akiraux/website#build-setup

In case needed we will open issues where we can discuss and anyone can make suggestions
